import { useState } from "react";
import Card from "./Card";

function Games() {
  const allGames = [
    {
      id: 1,
      title: "Cyberpunk 2077",
      minRam: "12 GB",
      minGpu: "GTX 1060",
      storage: "70 GB SSD",
      releaseYear: 2020,
    },
    {
      id: 2,
      title: "Elden Ring",
      minRam: "12 GB",
      minGpu: "GTX 1060",
      storage: "60 GB",
      releaseYear: 2022,
    },
    {
      id: 3,
      title: "Grand Theft Auto V",
      minRam: "4 GB",
      minGpu: "GT 9800",
      storage: "110 GB",
      releaseYear: 2015,
    },
    {
      id: 4,
      title: "Red Dead Redemption 2",
      minRam: "8 GB",
      minGpu: "GTX 770",
      storage: "150 GB",
      releaseYear: 2019,
    },
    {
      id: 5,
      title: "The Witcher 3: Wild Hunt",
      minRam: "6 GB",
      minGpu: "GTX 660",
      storage: "50 GB",
      releaseYear: 2015,
    },
    {
      id: 6,
      title: "Hogwarts Legacy",
      minRam: "16 GB",
      minGpu: "GTX 960",
      storage: "85 GB SSD",
      releaseYear: 2023,
    },
    {
      id: 7,
      title: "God of War (2018)",
      minRam: "8 GB",
      minGpu: "GTX 960",
      storage: "70 GB",
      releaseYear: 2022,
    },
    {
      id: 8,
      title: "Counter-Strike 2",
      minRam: "8 GB",
      minGpu: "GTX 660",
      storage: "85 GB",
      releaseYear: 2023,
    },
    {
      id: 9,
      title: "Dota 2",
      minRam: "4 GB",
      minGpu: "GT 8600",
      storage: "60 GB",
      releaseYear: 2013,
    },
    {
      id: 10,
      title: "Valorant",
      minRam: "4 GB",
      minGpu: "GT 730",
      storage: "43 GB",
      releaseYear: 2020,
    },
    {
      id: 11,
      title: "Alan Wake 2",
      minRam: "16 GB",
      minGpu: "RTX 2060",
      storage: "90 GB SSD",
      releaseYear: 2023,
    },
    {
      id: 12,
      title: "Baldur's Gate 3",
      minRam: "8 GB",
      minGpu: "GTX 970",
      storage: "150 GB SSD",
      releaseYear: 2023,
    },
    {
      id: 13,
      title: "Resident Evil 4 Remake",
      minRam: "8 GB",
      minGpu: "GTX 1050 Ti",
      storage: "60 GB",
      releaseYear: 2023,
    },
    {
      id: 14,
      title: "Forza Horizon 5",
      minRam: "8 GB",
      minGpu: "GTX 760",
      storage: "110 GB",
      releaseYear: 2021,
    },
    {
      id: 15,
      title: "Minecraft",
      minRam: "4 GB",
      minGpu: "GT 700",
      storage: "4 GB",
      releaseYear: 2011,
    },
    {
      id: 16,
      title: "Apex Legends",
      minRam: "6 GB",
      minGpu: "GTX 640",
      storage: "75 GB",
      releaseYear: 2019,
    },
    {
      id: 17,
      title: "Assassin's Creed Mirage",
      minRam: "8 GB",
      minGpu: "GTX 1060",
      storage: "40 GB SSD",
      releaseYear: 2023,
    },
    {
      id: 18,
      title: "Call of Duty: Warzone",
      minRam: "8 GB",
      minGpu: "GTX 960",
      storage: "125 GB",
      releaseYear: 2020,
    },
    {
      id: 19,
      title: "Spider-Man Remastered",
      minRam: "8 GB",
      minGpu: "GTX 950",
      storage: "75 GB SSD",
      releaseYear: 2022,
    },
    {
      id: 20,
      title: "Starfield",
      minRam: "16 GB",
      minGpu: "GTX 1070 Ti",
      storage: "125 GB SSD",
      releaseYear: 2023,
    },
    {
      id: 21,
      title: "Helldivers 2",
      minRam: "8 GB",
      minGpu: "GTX 1050 Ti",
      storage: "100 GB",
      releaseYear: 2024,
    },
    {
      id: 22,
      title: "Black Myth: Wukong",
      minRam: "16 GB",
      minGpu: "GTX 1060",
      storage: "130 GB SSD",
      releaseYear: 2024,
    },
    {
      id: 23,
      title: "Palworld",
      minRam: "16 GB",
      minGpu: "GTX 1050",
      storage: "40 GB SSD",
      releaseYear: 2024,
    },
    {
      id: 24,
      title: "FIFA 23 / EA Sports FC 24",
      minRam: "8 GB",
      minGpu: "GTX 1050 Ti",
      storage: "100 GB",
      releaseYear: 2023,
    },
    {
      id: 25,
      title: "Detroit: Become Human",
      minRam: "8 GB",
      minGpu: "GTX 780",
      storage: "55 GB",
      releaseYear: 2020,
    },
    {
      id: 26,
      title: "Horizon Zero Dawn",
      minRam: "8 GB",
      minGpu: "GTX 780",
      storage: "100 GB",
      releaseYear: 2020,
    },
    {
      id: 27,
      title: "Dead Space Remake",
      minRam: "16 GB",
      minGpu: "GTX 1070",
      storage: "50 GB SSD",
      releaseYear: 2023,
    },
    {
      id: 28,
      title: "League of Legends",
      minRam: "4 GB",
      minGpu: "GT 730",
      storage: "16 GB",
      releaseYear: 2009,
    },
    {
      id: 29,
      title: "Doom Eternal",
      minRam: "8 GB",
      minGpu: "GTX 1050 Ti",
      storage: "80 GB",
      releaseYear: 2020,
    },
    {
      id: 30,
      title: "Stardew Valley",
      minRam: "2 GB",
      minGpu: "GT 120",
      storage: "500 MB",
      releaseYear: 2016,
    },
  ];

  const [gamesArr, setGamesArr] = useState(allGames);
  // console.log(gamesArr);

  return (
    <div className="Games">
      {gamesArr.map((game) => (
        <Card gameObj={game} key={game.id} />
      ))}
    </div>
  );
}

export default Games;
